test oss files
facebookresearch/mobile-vision pull request #54
Opened 2021-09-21 05:34 UTC by zhanghang1989

2021-09-22 17:06 UTC, newstzpz requested changes

2021-09-22 17:06 UTC, newstzpz commented on mobile_cv/model_zoo/scripts/run_collect_models_det.py
> +#!/usr/bin/env python3
Remove the whole file.

2021-09-22 17:06 UTC, newstzpz commented on mobile_cv/model_zoo/scripts/run_create_model_benchmark.py
> +#!/usr/bin/env python3
Remove the whole file.

2021-09-22 17:06 UTC, newstzpz commented on mobile_cv/model_zoo/scripts/run_eval_model_zoo_cls.py
> +#!/usr/bin/env python3
Remove the whole file.

2021-09-22 17:06 UTC, newstzpz commented on mobile_cv/model_zoo/tests/test_datasets_classy.py
> +#!/usr/bin/env python3
Remove the whole file.

2021-09-22 17:06 UTC, newstzpz commented on mobile_cv/model_zoo/tests/test_job_queue_db.py
> +#!/usr/bin/env python3
Remove the whole file.

2021-09-22 17:06 UTC, newstzpz commented on mobile_cv/model_zoo/tests/test_model_zoo_classy.py
> +#!/usr/bin/env python3
Remove the whole file.

2021-09-22 17:06 UTC, newstzpz commented on mobile_cv/model_zoo/tests/test_model_zoo_fbnet.py
> +#!/usr/bin/env python3
Remove the whole file.

2021-09-22 17:06 UTC, newstzpz commented on mobile_cv/model_zoo/tests/test_model_zoo_vits.py
> +#!/usr/bin/env python3
Remove the whole file.

2021-09-23 00:39 UTC, zhanghang1989 commented on mobile_cv/common/misc/local_cache.py
> +import diskcache
Shall we ask people to install https://pypi.org/project/diskcache/ ?

2021-09-24 23:35 UTC, zhanghang1989 commented on mobile_cv/common/misc/local_cache.py
> +import diskcache
Added to the CI dependencies.

2021-09-28 23:07 UTC, zhanghang1989 commented
closing PR for deleting this branch. Will recreate one

2021-09-28 23:07 UTC, closed without merging